image: registry.gitlab.com/ultimaker/cura/cura-build-environment:centos7

stages:
  - build

build and test linux:
  stage: build
  tags:
    - cura
    - docker
    - linux
  script:
    - docker/build.sh
  artifacts:
    paths:
      - build

build-deb-mingw64:
  stage: build
  image: debian:buster
  tags:
    - cura
    - docker
    - linux
  before_script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install -y cmake gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 curl git
    - update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
    - update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
    - curl -1sLf 'https://dl.cloudsmith.io/public/ultimaker/cura-public/cfg/setup/bash.deb.sh' | bash
    - apt-get install -y cura-libprotobuf-mingw-w64-dev=3.9.2-1 cura-libprotobuf-dev=3.9.2-1 cura-libarcus-mingw-w64-dev=4.5.0-1
  script:
    - docker/build-deb-mingw64.sh
  artifacts:
    paths:
      - build
